# Generated by Django 4.2.6 on 2023-11-06 11:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_shortener.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_shortener', '0002_alter_url_options_url_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 11, 3, 22, 850416, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened_code',
            field=models.CharField(default=url_shortener.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
