# Generated by Django 4.2.6 on 2023-11-06 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_shortener', '0003_url_expired_date_alter_url_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 12, 20, 2, 23019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
