# Generated by Django 4.2.6 on 2023-11-06 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_alter_url_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 12, 33, 26, 342123, tzinfo=datetime.timezone.utc)),
        ),
    ]
