# Generated by Django 4.2.6 on 2023-11-06 12:36

from django.db import migrations, models
import url_shortener.models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0006_alter_url_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expired_date",
            field=models.DateTimeField(default=None),
        ),
    ]
