# Generated by Django 4.2.6 on 2023-11-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0010_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='expired_date',
        ),
    ]
