# Generated by Django 4.2.6 on 2023-11-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0012_alter_url_unique_together_alter_url_shortened_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='favicon',
            field=models.CharField(blank=True, max_length=100000000000000, null=True),
        ),
    ]
