# Generated by Django 4.2.6 on 2023-11-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0013_url_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.url')),
            ],
        ),
    ]
