# Generated by Django 4.2.6 on 2023-11-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0014_iprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprecord',
            name='recorded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
