# Generated by Django 4.2.6 on 2023-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0015_alter_iprecord_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
